# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'YYText'
  pod 'MJRefresh'
  pod 'XXDebugTool', '1.0.0'
  pod 'UITableView+FDTemplateLayoutCell'

end
